from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = BASE_DIR / "data"
MODELS_DIR = BASE_DIR / "models"

DATASET_PATH = DATA_DIR / "NF-UNSW-NB15-v2.csv"
SAMPLED_PATH = DATA_DIR / "dataset_sample.csv"

FEATURES = [
    'L4_SRC_PORT','L4_DST_PORT','PROTOCOL','L7_PROTO',
    'IN_BYTES','IN_PKTS','OUT_BYTES','OUT_PKTS',
    'TCP_FLAGS','CLIENT_TCP_FLAGS','SERVER_TCP_FLAGS',
    'FLOW_DURATION_MILLISECONDS','DURATION_IN',
    'MIN_TTL','MAX_TTL','LONGEST_FLOW_PKT','SHORTEST_FLOW_PKT',
    'MIN_IP_PKT_LEN','MAX_IP_PKT_LEN',
    'SRC_TO_DST_SECOND_BYTES','DST_TO_SRC_SECOND_BYTES',
    'SRC_TO_DST_AVG_THROUGHPUT','DST_TO_SRC_AVG_THROUGHPUT',
    'NUM_PKTS_UP_TO_128_BYTES',
    'TCP_WIN_MAX_IN','TCP_WIN_MAX_OUT',
    'ICMP_TYPE','ICMP_IPV4_TYPE',
    'DNS_QUERY_ID','DNS_QUERY_TYPE','DNS_TTL_ANSWER',
    'FTP_COMMAND_RET_CODE'
]